---
title: "Using A Multivariate Model to Understand How Youths’ In-The-Moment Engagement Predicts Changes in Youths’ Interest"
author: "Josh"
date: "12/07/2019"
output: html_document
---

```{r, setup-results-fix, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      collapse = TRUE,
                      fig.width = 6,
                      fig.asp = .618,
                      out.width = "80%", 
                      fig.align = "center", 
                      results = "hold", 
                      cache = TRUE) 

options(knitr.kable.NA = '')
set.seed(12345)
```

## Loading data, setting up

```{r, load-packages-load-data, echo = FALSE}
library(tidyverse)
library(brms)

d_red <- read_csv("processed-data/data-to-model.csv")

d_for_m2 <- filter(d_red, !is.na(gender_female) & !is.na(pre_interest)) # if there are missing vals in the fixed predictors, MCMCglmm gives a warning

d_for_m2 <- fill(d_for_m2, pre_interest, post_interest)

d_for_m2 <- d_for_m2 %>% 
  mutate(creating_product = ifelse(youth_activity_rc == "Creating Product", 1, 0),
         lab_activity = ifelse(youth_activity_rc == "Lab Activity", 1, 0))

d_for_m2 <- d_for_m2 %>% 
  rename(lab_activity_prop = `Lab Activity`,
         creating_product_prop = `Creating Product`)
```

# Null model

```{r}
bf_0_1 <- bf(interest ~ 1 +
               (1|s|beep_ID_new) +
               (1|p|participant_ID) +
               (1|q|program_ID))

bf_0_2 <- bf(post_interest ~ 1 +
               (1|s|beep_ID_new) +
               (1|p|participant_ID) +
               (1|q|program_ID))

m0 <- brm(bf_0_1 + bf_0_2,
          data = d_for_m2, 
          chains = 4, cores = 4, iter = 500)
```

# Full model, without the program random effect

```{r}
bf_1 <- bf(interest ~ 1 +
             challenge +
             relevance +
             gender_female + 
             pre_interest +
             creating_product +
             lab_activity + 
             (1|s|beep_ID_new) +
             (1|p|participant_ID))

bf_2 <- bf(post_interest ~ 1 +
             prop_attend +
             gender_female + 
             pre_interest +
             lab_activity_prop +
             creating_product_prop +
             (1|s|beep_ID_new) +
             (1|p|participant_ID))

m1a <- brm(bf_1 + bf_2,
           data = d_for_m2, 
           chains = 4, cores = 4, iter = 1000)
```

# Full model, full random effects structure

```{r}
bf_1 <- bf(interest ~ 1 +
             challenge +
             relevance +
             gender_female + 
             pre_interest +
             creating_product +
             lab_activity + 
             (1|s|beep_ID_new) +
             (1|p|participant_ID) +
             (1|q|program_ID))

bf_2 <- bf(post_interest ~ 1 +
             prop_attend +
             gender_female + 
             pre_interest +
             lab_activity_prop +
             creating_product_prop +
             (1|s|beep_ID_new) +
             (1|p|participant_ID) +
             (1|q|program_ID))

m1 <- brm(bf_1 + bf_2,
          data = d_for_m2, 
          chains = 4, cores = 4, iter = 1000)
```
