---
title: "Using A Multivariate Model to Understand How Youths’ In-The-Moment Engagement Predicts Changes in Youths’ Interest"
author: "Joshua M. Rosenberg"
date: "10/22/2019"
output: html_document
---

```{r, setup-results-fix, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      collapse = TRUE,
                      fig.width = 6,
                      fig.asp = .618,
                      out.width = "80%", 
                      fig.align = "center", 
                      results = "hold", 
                      cache = TRUE) 

options(knitr.kable.NA = '')
set.seed(12345)
```

# Loading data, setting up

```{r, load-packages-load-data}
library(tidyverse)
library(MCMCglmm)
library(brms)

d_red <- read_csv("processed-data/data-to-model.csv")

d_for_m2 <- filter(d_red, !is.na(gender_female) & !is.na(pre_interest)) # if there are missing vals in the fixed predictors, MCMCglmm gives a warning
```

# Results using MCMCglmm

```{r, MCMC-model, eval = FALSE}
prior = list(R = list(V = diag(c(1, 0.0001), 2, 2), nu = 0.002, fix = 2),
             G = list(G1 = list(V = diag(2), nu = 2,
                                alpha.mu = rep(0, 2),
                                alpha.V = diag(25^2, 2, 2)),
                      G2=list(V = diag(2),
                              n = 2,
                              alpha.mu = rep(0, 2),
                              alpha.V  = diag(25^2, 2, 2))))

m2 <- MCMCglmm(fixed = cbind(rm_engagement, post_interest) ~ trait + 
                 trait:gender_female + 
                 trait:pre_interest,
               random =~ us(trait):participant_ID + us(trait):program_ID,
               rcov = ~ idh(trait):units,
               family = rep("gaussian",2),
               data = as.data.frame(d_for_m2),
               prior = prior,
               burnin = 5000,
               nitt = 100000,
               thin = 40,
               verbose = TRUE)
```

```{r, mcmc-summary,eval=F}
summary(m2)
```

This creates a lot of plots
```{r, mcmc-plots, fig.height=50,eval=F}
plot(m2)
```

```{r, cov,eval=F}
m2_cor <- m2$VCV[,"traitpost_interest:traitrm_engagement.participant_ID"]/
  (sqrt(m2$VCV[,"traitpost_interest:traitpost_interest.participant_ID"])*
     sqrt(m2$VCV[,"traitrm_engagement:traitrm_engagement.participant_ID"]))

posterior.mode(m2_cor)
HPDinterval(m2_cor)
#plot(m2_cor)

m2_cor2 <- m2$VCV[,"traitpost_interest:traitrm_engagement.program_ID"]/
  (sqrt(m2$VCV[,"traitpost_interest:traitpost_interest.program_ID"])*
     sqrt(m2$VCV[,"traitrm_engagement:traitrm_engagement.program_ID"]))

posterior.mode(m2_cor2)
HPDinterval(m2_cor2)
#plot(m2_cor)

ind_icc <- m2$VCV[,"traitrm_engagement:traitrm_engagement.participant_ID"]/(m2$VCV[,"traitrm_engagement:traitrm_engagement.participant_ID"] + m2$VCV[,"traitrm_engagement.units"])

posterior.mode(ind_icc)
HPDinterval(ind_icc)

ind_icc2 <- m2$VCV[,"traitpost_interest:traitpost_interest.participant_ID"]/(m2$VCV[,"traitpost_interest:traitpost_interest.participant_ID"] + m2$VCV[,"traitpost_interest.units"])

posterior.mode(ind_icc2)
HPDinterval(ind_icc2)

prog_icc <- m2$VCV[,"traitrm_engagement:traitrm_engagement.program_ID"]/(m2$VCV[,"traitrm_engagement:traitrm_engagement.program_ID"] + m2$VCV[,"traitrm_engagement.units"])

posterior.mode(prog_icc)
HPDinterval(prog_icc)

prog_icc2 <- m2$VCV[,"traitpost_interest:traitpost_interest.program_ID"]/(m2$VCV[,"traitpost_interest:traitpost_interest.program_ID"] + m2$VCV[,"traitpost_interest.units"])

posterior.mode(prog_icc2)
HPDinterval(prog_icc2)
```

# Results using brms

```{r}
d_for_m2 <- d_for_m2 %>% 
  group_by(participant_ID) %>% 
  mutate(signal_number = row_number()) %>% 
  ungroup()
```

```{r}
m3 <- brm(mvbind(rm_engagement, post_interest) ~ 
            gender_female + 
            pre_interest +
            (1|p|participant_ID) +
            autocor = cor_ar(~ signal_number | participant_ID),
          data = d_for_m2, 
          chains = 4, cores = 4, iter = 500,
          control = list(adapt_delta = .999,
                         max_treedepth = 15))
```

```{r}
bf_1 <- bf(rm_engagement~ gender_female + pre_interest + (relevance|p|participant_ID))
bf_2 <- bf(post_interest ~ gender_female + pre_interest + (1|p|participant_ID))

m4 <- brm(bf_1 + bf_2,
          data = d_for_m2, 
          chains = 4, cores = 4, iter = 750)

bf_2_1 <- bf(rm_engagement~ gender_female + pre_interest + signal_number + (relevance + signal_number|p|participant_ID))
bf_2_2 <- bf(post_interest ~ gender_female + pre_interest + (1|p|participant_ID))

m5 <- brm(bf_2_1 + bf_2_2,
          autocor = cor_ar(~ signal_number | participant_ID),
          data = d_for_m2, 
          chains = 4, cores = 4, iter = 750)
```