---
title: "MCMCglmm test"
author: "Joshua Rosenberg"
date: "3/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

```{r, example-from-jarred-hadfield}
library(MCMCglmm)

N<-500
# 500 individuals

V<-matrix(c(1,0.5, 0.5, 1),2,2)
# 2x2 random/residual-effect covariance matrix

Vr<-matrix(1,1,1)
# residual variance for repeat measure trait

u<-MASS::mvrnorm(N, rep(0, 2), V)
# random effect for repeat measure trait followed by
# residuals for the single measured trait.

e<-rnorm(2*N,0,sqrt(Vr))
# residuals for the repeat trait

ysingle<-1+u[,2]
# single measure traits has intercept of 1

individual<-as.factor(rep(1:N, 3))
# individuals are ordered within each trait/time combination

type<-as.factor(c(rep("s", N), rep("r",2*N)))
# designate which observations are single measures (s)
# or repeat measures (r)

yrep<--1+u[rep(1:N, 2),1]+e
# the repeat measure trait has an intercept of -1

dat1<-data.frame(y=c(ysingle,yrep), type=type,
                 individual=individual)

prior1<-list(R=list(R1=list(V=V, nu=0, covu=TRUE),
                    R2=list(V=Vr, nu=0)))

str(dat1)

# use flat priors, but use covu=TRUE to mdoel covariances
# between R1 effects and the random effects
# (G is not needed because random effect prior is
#  specified in R1)

m.test1<-MCMCglmm(y~type-1,
                  random=~us(at.level(type,"r")):individual,
                  rcov=~us(at.level(type, "s")):individual+us(at.level(type, "r")):units,
                  data=dat1,
                  prior=prior1,
                  verbose=FALSE)

summary(m.test1)
```

# Josh example 

```{r}

library(tidyverse)
library(MCMCglmm)

d <- read_csv("mcmcglmm-data.csv")

# N<-500
# # 500 individuals

V<-matrix(c(1,0.5, 0.5, 1),2,2)
# 2x2 random/residual-effect covariance matrix

Vr<-matrix(1,1,1)
# residual variance for repeat measure trait

prior1<-list(R=list(R1=list(V=V, nu=0, covu=TRUE),
                    R2=list(V=Vr, nu=0)))

# Preparing data 
ind <- distinct(d, participant_ID, overall_pre_interest)
rep <- select(d, participant_ID, overall_engagement)
type <- c(rep("s", nrow(ind)), rep("r", nrow(rep)))

dd <- data.frame(y = c(ind$overall_pre_interest, rep$overall_engagement),
                 type = as.factor(type),
                 individual = as.factor(c(as.character(ind$participant_ID), as.character(rep$overall_engagement))))

m.test2 <- MCMCglmm(y ~ type-1,
                    random=~us(at.level(type,"r")):individual,
                    rcov=~us(at.level(type, "s")):individual + us(at.level(type, "r")):units,
                    data=dd,
                    prior=prior1,
                    verbose=FALSE)

summary(m.test2)
```
